### ISSUE TITLE
ZINT for 4D Mac Notarization

### ISSUE THREAD

**Issue by keithculotta** [miyako/4d-plugin-zint-v2#1]
Hello,

I'm opening this issue after reading the forums.4d.com message you sent.  I would notarize the plugin for Catalina myself if I had any idea how to do that.  I imagine it is more involved than notarizing a 4D built app.  If you could point me to a starting point, I will take a look at it.

Thanks, Keith Culotta

**Comment by miyako** [comment]
could you please try 3.2.v18 or 3.2.v17?

**note**: you need to download from resources.
