### ISSUE TITLE
Error « json malformed… » V17.5 Win 10

### ISSUE THREAD

**Issue by Pacific745** [miyako/4d-plugin-zint-v2#4]
I don’t know why, on some computer I get this error.
i reinstall windows 10, try 17.4, try many thing but I still have the same error when I start 4D.
It’s not only zint, but also XLS 2, all the other plugins are working.
Picture of the error:
https://www.dropbox.com/s/x47c21ecevxr92f/IMG_0950.jpg?dl=0
regards.

**Comment by miyako** [comment]
can you post the content of the malformed .json file?

**Comment by miyako** [comment]
keep in mind that v17 does not look for manifest.json inside Resources.

you need to move the file inside Resources one level up to inside Contents, to use the plugin with v17.

**Comment by miyako** [comment]
it looks like you also have issues with constants.xlf.

is it possible that a security software is erasing these files?

but I repeat, the error dialog is telling the path, you should look what that files look like.

**Comment by Pacific745** [comment]
The json file:
Picture:
https://www.dropbox.com/s/t9rixjbdkof3mfa/Capture.JPG?dl=0

File:
https://www.dropbox.com/s/nehorvnocbikkri/manifest.json?dl=0

**Comment by Pacific745** [comment]
This is the place of the file:

https://www.dropbox.com/s/9ot9u8mfbk05ajo/Capture2.JPG?dl=0

And as you can see in the path of the error it's good:
![image](https://user-images.githubusercontent.com/92851044/138229475-80884266-66f2-4469-bf23-50e1cab9cb26.jpeg)

**Comment by Pacific745** [comment]
I reinstall windows, and no extra software. 
I know the config is low but:
![image](https://user-images.githubusercontent.com/92851044/138230044-4c36044f-e153-4b29-b679-6999a418dceb.jpeg)
For information I have 1 other computer where it's working well.

**Comment by miyako** [comment]
the file content is important. the error message didn't say the file is missing.

**Comment by miyako** [comment]
maybe the file has a bom or someother invisible character. you might need a code editor or hex editor to see it. 

maybe you used a bad archive or bad copy method to install the plugin.

**Comment by Pacific745** [comment]
I reinstall 4D on a new computer.
And I get the same result.
![image](https://user-images.githubusercontent.com/92851044/138232719-454e7b98-0b15-4027-ac58-d221a87bd82a.jpeg)

Config:
![image](https://user-images.githubusercontent.com/92851044/138232744-27e3d42e-8c14-49bb-9652-1907d0d6430d.jpeg)

**Comment by miyako** [comment]
based on your reports it is unlikely to be caused by windows or 4D. it sounds like the plugin is not copied correctly.

**Comment by Pacific745** [comment]
Thank you for the information of "not copied correctly", I zip the plug-in before the copy, then I copy and extract and everything is working well. It's the USB key who break something.
Thank you again.
